// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudGax
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The response structure for the ListResourceMaintenances method.
public struct ListResourceMaintenancesResponse: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  GoogleCloudGax._PaginatedResponse,
  Sendable
{
  /// The resulting resource maintenances.
  public var resourceMaintenances: [ResourceMaintenance] = []

  /// If present, the next page token can be provided to a subsequent
  /// ListResourceMaintenances call to list the next page.
  /// If empty, there are no more pages.
  public var nextPageToken: Swift.String = Swift.String()

  /// Locations that could not be reached.
  public var unreachable: [Swift.String] = []

  /// Initialize a new instance of `ListResourceMaintenancesResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListResourceMaintenancesResponse().with { $0.resourceMaintenances = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.maintenance.api.v1.ListResourceMaintenancesResponse"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }

  public func _getPaginatedItems() -> [ResourceMaintenance] {
    return self.resourceMaintenances
  }

  public func _nextPageToken() -> Swift.String {
    return self.nextPageToken
  }
}
