// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// MaintenanceSummary contains maintenance statistics calculated based on
/// ResourceMaintenances within the scope: project and location.
public struct MaintenanceSummary: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The name of the maintenance.
  public var maintenanceName: Swift.String = Swift.String()

  /// Output only. The title of the maintenance.
  public var title: Swift.String = Swift.String()

  /// Output only. The description of the maintenance.
  public var description: Swift.String = Swift.String()

  /// Output only. The category of the maintenance event.
  public var category: MaintenanceCategory = MaintenanceCategory()

  /// Output only. Scheduled start time of the maintenance. The maintenance will
  /// start at `maintenanceScheduledStartTime` or later, with best effort to
  /// finish before `maintenanceScheduledEndTime`.
  public var maintenanceScheduledStartTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. An estimated (best effort, not guaranteed) end time of the
  /// scheduled maintenance.
  public var maintenanceScheduledEndTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Actual date when the maintenance started. Field present only
  /// after the state changed to `RUNNING`.
  public var maintenanceStartTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Actual date when the maintenance successfully completed. Field
  /// present only after the state changed to `SUCCEEDED`.
  public var maintenanceEndTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Indicates whether the user has some control over that
  /// maintenance, either proactively before maintenance was scheduled with
  /// maintenance policy or with reactive controls after it was scheduled (see
  /// controls field).
  public var userControllable: Swift.Bool = Swift.Bool()

  /// Output only. Control available for that Maintenance (might not be available
  /// for every resource that maintenance is applied to).
  public var controls: [MaintenanceControl] = []

  /// Output only. Stats is a field of ResourceMaintenance used to aggregate the
  /// stats.
  public var stats: [MaintenanceSummary.Stats] = []

  /// Initialize a new instance of `MaintenanceSummary`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = MaintenanceSummary().with { $0.maintenanceName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Stats indicates the type of aggregate and the corresponding aggregates.
  public struct Stats: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// groupBy specifies the type of aggregate.
    /// For example a group_by might be `"state"`
    public var groupBy: Swift.String = Swift.String()

    /// Aggregates is a list <group, count> pairs. For example, if the
    /// group_by is `"state"` a possible tuple in the aggregates list could be
    /// "SCHEDULED" : `11`,
    public var aggregates: [MaintenanceSummary.Aggregate] = []

    /// Initialize a new instance of `Stats`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Stats().with { $0.groupBy = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.maintenance.api.v1.MaintenanceSummary.Stats"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Aggregate is a <group, count> pair.
  public struct Aggregate: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Specifies what specific value of the group_by the count represents. For
    /// example if group_by is `"state"` its corresponding group could be
    /// `"SCHEDULED"`.
    public var group: Swift.String = Swift.String()

    /// The count of the group.
    public var count: Swift.Int64 = Swift.Int64()

    /// Initialize a new instance of `Aggregate`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Aggregate().with { $0.group = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.maintenance.api.v1.MaintenanceSummary.Aggregate"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.maintenance.api.v1.MaintenanceSummary"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
