// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// ResourceMaintenance is a resource that represents a maintenance operation
/// on a resource.
public struct ResourceMaintenance: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. The name of the resource_maintenance resource.
  /// Format:
  /// `"projects/{project}/locations/{location}/resourceMaintenance/{resource-maintenance-id}"`
  public var name: Swift.String = Swift.String()

  /// Output only. The resource spec of the resource maintenance.
  public var resource: ResourceMaintenance.Resource? = nil

  /// Output only. The details of the maintenance.
  public var maintenance: ResourceMaintenance.Maintenance? = nil

  /// Output only. The state of the resource maintenance.
  public var state: ResourceMaintenance.State = ResourceMaintenance.State()

  /// Output only. The create time of the resource maintenance.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The update time of the resource maintenance.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The time when the resource maintenance has started.
  public var maintenanceStartTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The time when the resource maintenance has completed.
  public var maintenanceEndTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The time when the resource maintenance was cancelled.
  public var maintenanceCancelTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The time when the maintenance on the resource was scheduled to
  /// start.
  public var maintenanceScheduledStartTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The time when the maintenance on the resource was scheduled to
  /// end.
  public var maintenanceScheduledEndTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Indicates whether the user has some control over that
  /// maintenance, either proactively before maintenance was scheduled with
  /// maintenance policy or with reactive controls after it was scheduled (see
  /// controls field)
  public var userControllable: Swift.Bool = Swift.Bool()

  /// Output only. The controls of the maintenance.
  public var controls: [MaintenanceControl] = []

  /// Optional. The labels on the resource, which can be used for categorization.
  /// similar to Kubernetes resource labels.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. Annotations is an unstructured key-value map stored with a
  /// resource that may be set by external tools to store and retrieve arbitrary
  /// metadata. They are not queryable and should be preserved when modifying
  /// objects.
  ///
  /// More info: https://kubernetes.io/docs/user-guide/annotations
  public var annotations: [Swift.String: Swift.String] = [:]

  /// Output only. The unique identifier of the resource. UID is unique in the
  /// time and space for this resource within the scope of the service. It is
  /// typically generated by the server on successful creation of a resource
  /// and must not be changed. UID is used to uniquely identify resources
  /// with resource name reuses. This should be a UUID4.
  public var uid: Swift.String = Swift.String()

  /// Output only. An opaque value that uniquely identifies a version or
  /// generation of a resource. It can be used to confirm that the client
  /// and server agree on the ordering of a resource being written.
  public var etag: Swift.String = Swift.String()

  /// Initialize a new instance of `ResourceMaintenance`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ResourceMaintenance().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Resource contains information about the resource affected by maintenance.
  public struct Resource: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Output only. Name is the reference to the consumer resource affected by
    /// the maintenance. Available values can be found here:
    /// https://cloud.google.com/asset-inventory/docs/asset-names
    public var resourceName: Swift.String = Swift.String()

    /// Output only. The location of the resource.
    /// Format:
    /// `us-central1`
    public var location: Swift.String = Swift.String()

    /// Output only. The type of the resource.
    /// Available values can be found here:
    /// https://cloud.google.com/asset-inventory/docs/asset-types#supported_resource_types
    /// Please note that not all the resource types will have their maintenances
    /// reported.
    public var type: Swift.String = Swift.String()

    /// Initialize a new instance of `Resource`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Resource().with { $0.resourceName = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.maintenance.api.v1.ResourceMaintenance.Resource"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Maintenance is the maintenance details of a resource's maintenance.
  public struct Maintenance: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Maintenance is the name of the corresponding maintenance resource
    /// following the standard naming scheme: `"{maintenance-id}"`
    public var maintenanceName: Swift.String = Swift.String()

    /// Output only. The title of the maintenance.
    public var title: Swift.String = Swift.String()

    /// Output only. The description of the maintenance.
    public var description: Swift.String = Swift.String()

    /// Output only. The category of the maintenance.
    public var category: MaintenanceCategory = MaintenanceCategory()

    /// Initialize a new instance of `Maintenance`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Maintenance().with { $0.maintenanceName = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.maintenance.api.v1.ResourceMaintenance.Maintenance"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// State is the state of a resource maintenance.
  public enum State: Codable, Equatable, Sendable {
    /// Unspecified state.
    case unspecified
    /// Scheduled for a particular window. For disruptive maintenance it should
    /// respect maintenance policy, i.e. its available windows, exclusions and
    /// notification period.
    case scheduled
    /// Maintenance is ongoing.
    case running
    /// No longer planned, typically when other maintenance (e.g. upgrade to
    /// newer version) already happened, or the user skipped the maintenance.
    case cancelled
    /// Successfully completed.
    case succeeded
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .scheduled: return 1
      case .running: return 2
      case .cancelled: return 3
      case .succeeded: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .scheduled: return "SCHEDULED"
      case .running: return "RUNNING"
      case .cancelled: return "CANCELLED"
      case .succeeded: return "SUCCEEDED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "SCHEDULED": self = .scheduled
      case "RUNNING": self = .running
      case "CANCELLED": self = .cancelled
      case "SUCCEEDED": self = .succeeded
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .scheduled
      case 2: self = .running
      case 3: self = .cancelled
      case 4: self = .succeeded
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .scheduled: return try container.encode(1)
      case .running: return try container.encode(2)
      case .cancelled: return try container.encode(3)
      case .succeeded: return try container.encode(4)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.maintenance.api.v1.ResourceMaintenance"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
