// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for SummarizeMaintenances custom method.
public struct SummarizeMaintenancesRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The parent of the resource maintenance.
  /// eg. `projects/123/locations/*`
  public var parent: Swift.String = Swift.String()

  /// The maximum number of resource maintenances to send per page. The default
  /// page size is 20 and the maximum is 1000.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// The page token: If the next_page_token from a previous response
  /// is provided, this request will send the subsequent page.
  public var pageToken: Swift.String = Swift.String()

  /// Filter the list as specified in https://google.aip.dev/160.
  /// Supported fields include:
  /// - `maintenance.maintenanceName`
  /// Examples:
  /// - `maintenance.maintenanceName="eb3b709c-9ca1-5472-9fb6-800a3849eda1"`
  public var filter: Swift.String = Swift.String()

  /// Order results as specified in https://google.aip.dev/132.
  public var orderBy: Swift.String = Swift.String()

  /// Initialize a new instance of `SummarizeMaintenancesRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SummarizeMaintenancesRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.maintenance.api.v1.SummarizeMaintenancesRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
